---
title: "Integração Python em R e R em Python"
---
```{r echo = FALSE}
if (!require("pacman")) install.packages("pacman")
p_load(reticulate)
```

<section class="title-slide">
    <h1 style="text-align: center">Python no R</h1>
</section>

<section>
<h2>Reticulate:</h2>
<h3>Scripts do Python no R</h3>

:::::: {.columns}

:::: {.column width="50%"}
- Execução de scripts do Python interagindo com a sessão do R; 
- Tradução entre objetos do R e do Python (como entre data frames do R e do Pandas);
::::

:::: {.column width="50%"}
::: {.fragment}

```{r}
library(reticulate)
use_virtualenv("./venv", required = T)

# py_install("numpy");

repl_python()
```

```{python}
import pandas as pd
import numpy as np
py_arr = np.array([1, 2, 3, 4, 5])
for item in py_arr:
  print(item, end=", ")
```

```{r}
r_arr <- as.vector(py$py_arr)
print(r_arr)
```
::: 
::::
::::::
</section>

</section>

<section>
<h2>Rpy2:</h2>
<h3>Códigos do R no Python</h3>
</section>

<section>
<h2>Rcpp:</h2>
<h3>C++ no R</h3>

:::::: {.columns}

:::: {.column width="50%"}
- Veloz
- Eficiente
::::
::::::
</section>


<section>
<h2>DLL:</h2>
<h3>C++ no Python</h3>
</section>